# Generated by Django 4.2 on 2023-04-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_movie_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='coordinates',
            field=models.TextField(blank=True, default=None),
        ),
    ]
